apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: anika-csr
spec:
  groups:
    - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2JqQ0NBVllDQVFBd0tURU1NQW9HQTFVRUF3d0RjR0Z0TVJrd0Z3WURWUVFLREJCa1lYUmhMV1Z1WjJsdQpaV1Z5YVc1bk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBdVZqb0hzMXpoREU5CjdkTU03VzB5U0dqZGpLeEIrUExDRU10Qm12WmZtWjBNU1VEWFBaSElnNlM0OEJsVndvZnVrRmdpU2MvZ2h5NzMKNVRMRTZsRkEzQ1VKOHZYR2ZjT1BlVEsrTlFOYWxKUXJkMTZmbjVXWFNLSkpGMS9NSENvbmduTkN2NnFtb1hnYgo3Z2hYQ1FsSE5FWHlzK2VQZkJ6dXY1Q25uRk1GM3ZMMllURERDZVdjQ2hIbWUydWkzSjhjaEZFSW9DSUxqaXR1CmcrajFLR2RvQUQwUlBUalRNVElwMENmSzVsR050aFJ2VFJQV2ZqSC9QbThxOFpobnduRTlPNUN3a3JTVXdPTHEKekt0UlNWWktwTXZnQ043d09PYmNzOXpJY2wrc2ZoYXJYUGF5Mm5Fbk1jQkVjQ0hNUmUyeWl6ZjBtVG51eXlNQgptOUZuK3pSUE53SURBUUFCb0FBd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFHQ3RNbFNpVWFvMVNpL1dmY2xvClYzNzlJamFsSDVjYlFscUZhWWttM1FYUGZLRlkrT3cvOEhSellYS1YzZHpOQVZJckJ3b0FVNVQzbVR3U0hKU08KTTRhNlI1TGFVc3Z0aUtSeVZqT1NTYnh2T09ZWkRXOWRrZVg5b2FqSHBWZmdpWmJnR1NLbUZpZHVkTE5WNVdsTgpUK0U0SmFUQ01sbFJ5eVI2LzBHTjNOTGczR3pyenhNbnkrNkVKcXdqWE9OMGZCTXdoQmQxZTZkcW9TVFpOK3lzCmNFZHpkeUJTNEQ5TFRKRTV4V1JGVjd3aDRzbTVTSFhiUmFJbWhGYjgyZW5aZGpIb3ExR0lwbmRPYklDVGZZR04KVjBjQ1RRL3ovbUdoczFuRUlKSWZycHhEQlByZkJpU0h2U1JqZmRZclVnTnlaaTVMVm9XWHR1SUR6K0VNK3BhawpScDQ9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  usages:
  - digital signature
  - key encipherment
